# Etapa 1: Construcción (Build)
FROM node:20-alpine AS builder

WORKDIR /app

# Copiamos los archivos de dependencias primero para aprovechar la caché de Docker
COPY package*.json ./
RUN npm install

# Copiamos todo el código fuente
COPY . .

# Construimos la aplicación NestJS (genera la carpeta /dist)
RUN npm run build

# Etapa 2: Producción (Imagen final súper ligera)
FROM node:20-alpine

WORKDIR /app

# Copiamos solo los package.json y instalamos SOLO las dependencias de producción
COPY package*.json ./
RUN npm install --omit=dev

# Traemos la carpeta /dist ya compilada de la etapa anterior
COPY --from=builder /app/dist ./dist

# Exponemos el puerto que usará tu app (Cloudflare Tunnels o Oracle usarán esto)
EXPOSE 3000

# Comando para arrancar la app
CMD ["node", "dist/main.js"]